### ISSUE TITLE
missing script: upgradeps

### ISSUE THREAD

**Issue by HansCronau** [lropero/upgradeps#3]
Following installation instructions for npm without npx yields the following error:

`npm ERR! missing script: upgradeps`

There is indeed no entry `upgradeps` in `scripts` (`package.json`).

**Comment by HansCronau** [comment]
Workaround: manually add `"upgradeps": "upgradeps",` to `scripts`.

**Comment by lropero** [comment]
Hi @HansCronau, just checked this and it turns out npm doesn't support running `bin` script as yarn does so you should manually execute `./node_modules/.bin/upgradeps` after installing, or as you already did, create the following script line in `package.json` before doing `npm run upgradeps`:
```
"scripts": {
  "upgradeps": "upgradeps"
},
```

Please note this is not necessary if using yarn, `yarn run upgradeps` works fine without needing to add this line. I'll update documentation shortly.
